// <auto-generated />
namespace MechanicTracker.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MemberShip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MemberShip));
        
        string IMigrationMetadata.Id
        {
            get { return "201502151258154_MemberShip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
