// <auto-generated />
namespace MechanicTracker.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Authentication : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Authentication));
        
        string IMigrationMetadata.Id
        {
            get { return "201502221039035_Authentication"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
