//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechanicTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobscategory
    {
        public jobscategory()
        {
            this.jobslists = new HashSet<jobslist>();
        }
    
        public sbyte JobsCategoryID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<jobslist> jobslists { get; set; }
    }
}
