//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechanicTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobslist
    {
        public jobslist()
        {
            this.jobs = new HashSet<job>();
            this.model_jobslist = new HashSet<model_jobslist>();
        }
    
        public short JobsListID { get; set; }
        public sbyte JobCategoryID { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<job> jobs { get; set; }
        public virtual jobscategory jobscategory { get; set; }
        public virtual ICollection<model_jobslist> model_jobslist { get; set; }
    }
}
