//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechanicTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class make
    {
        public make()
        {
            this.models = new HashSet<model>();
        }
    
        public short MakeID { get; set; }
        public string MakeName { get; set; }
    
        public virtual ICollection<model> models { get; set; }
    }
}
