//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechanicTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class model
    {
        public model()
        {
            this.cars = new HashSet<car>();
            this.model_jobslist = new HashSet<model_jobslist>();
        }
    
        public int ModelID { get; set; }
        public string ModelName { get; set; }
        public short MakeID { get; set; }
    
        public virtual ICollection<car> cars { get; set; }
        public virtual make make { get; set; }
        public virtual ICollection<model_jobslist> model_jobslist { get; set; }
    }
}
