//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechanicTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class model_jobslist
    {
        public int ModelID { get; set; }
        public short JobslistID { get; set; }
        public short ApproxTime { get; set; }
        public sbyte Difficulty { get; set; }
    
        public virtual jobslist jobslist { get; set; }
        public virtual model model { get; set; }
    }
}
