//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechanicTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int NotificationID { get; set; }
        public int MechanicID { get; set; }
        public System.DateTime Date { get; set; }
        public string Message { get; set; }
        public bool Read { get; set; }
        public int JobID { get; set; }
    
        public virtual mechanic mechanic { get; set; }
        public virtual job job { get; set; }
    }
}
